- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install Docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: pull the docker image
    command: docker pull devopsedu/webapp
  - name: create container
    command: docker run -itd -P devopsedu/webapp
